# fly.toml app configuration file generated for billowing-paper-1085 on 2023-08-28T13:02:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-paper-1085"
primary_region = "nrt"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_URL = "https://billowing-paper-1085.fly.dev"
  APP_NAME = "Laravel"
  APP_DEBUG = false
  APP_ENV = "production"
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.suydzogwpjdirnrrfrki.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
